{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
package:
  name: serial-device
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  #: .. versionadded:: 0.10
  noarch: python

requirements:
  build:
    - paho-mqtt-helpers
    - pandas >=0.18
    - path_helpers
    - pyserial
    - python
    #: .. versionadded:: 0.10
    - versioneer

  run:
    - paho-mqtt-helpers
    - pandas >=0.18
    - path_helpers
    - pyserial
    - python

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../
